<%@page import="java.util.List"%>
<%@page import="java.util.LinkedList"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ page import = "java.sql.*" %>
<%!
private List<String> resetDatabase(boolean force) throws Exception {
        LinkedList<String> messages = new LinkedList();
        /* How to customize:
         * 1. Update the database name on dbname.
         * 2. Create the list of tables, under tablenames[].
         * 3. Create the list of table definition, under tables[].
         * 4. Create the data into the above table, under data[]. 
         * 
         * If there is any problem, it will exit at the very first error.
         */
        String dbname = "dbpract1";
        Class.forName("org.apache.derby.jdbc.ClientDriver");
        /* this will generate database if not exist */
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname + ";create=true", "user", "pwd");
        Statement stmt = con.createStatement();

        try {
            stmt.execute("CREATE SCHEMA " + dbname);
            // schema was created; it will appear into: Other schemas -> "dbname"
        } catch (SQLException e) {
            // schema already exists; do nothing.
            if (!force) {
                messages.add("Database exists. Doing nothing. Visit install.jsp on your browser to reset your database content.");
                return messages;
            }
        }

        /* drop tables if they exist */
        String tablenames[] = new String[]{
            "professors","treballs","tfgVsDirector","tfgVsEstudiant"};
        for (String tablename : tablenames) {
            try {
                stmt.executeUpdate("DROP TABLE " + dbname + "." + tablename);
                messages.add("<pre> -> DROP TABLE " + dbname + "." + tablename + "<pre>");
            } catch (SQLException e) {
                // table didn't exist; it is the first time
            }
        }

        /* creating tables */
        String tables[] = new String[]{
            "CREATE TABLE " + dbname + ".professors ("
            + " id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),"
            + " username VARCHAR(20), password VARCHAR(20), nomcomplet VARCHAR(80))",
            "CREATE TABLE " + dbname + ".treballs ("
            + " id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),"
            + " titol VARCHAR(30), descripcio VARCHAR(300), estat VARCHAR(15), estudis VARCHAR(70), recursos VARCHAR(150),"
            + " dataDefensa DATE, nota VARCHAR(3), dataCreacio DATE, dataModificacio DATE)",
            "CREATE TABLE " + dbname + ".tfgVsDirector ("
            + " id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),"
            + " treball_id INT, professor_id INT",
            "CREATE TABLE " + dbname + ".tfgVsEstudiant ("
            + " id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),"
            + " treball_id INT, estudiant VARCHAR(30))"};
        for (String table : tables) {
            try {
                stmt.execute(table);
            } catch (SQLException e) {
                messages.add("<span class='error'>Error creating table: " + table + "</span>");
                return messages;
            }
            messages.add("<pre> -> " + table + "<pre>");
        }

        /* inserting data */
        /* you have to exclude the id autogenerated from the list of columns if you have use it. */
        String data[] = new String[]{
            "INSERT INTO " + dbname + ".professors (username,password,nomcomplet) VALUES ('sob','sob','Sistemes Oberts')",
            "INSERT INTO " + dbname + ".professors (username,password,nomcomplet) VALUES ('marc','123','Marc Sánchez')",
            "INSERT INTO " + dbname + ".professors (username,password,nomcomplet) VALUES ('santi','321','Santiago Romaní')",
            "INSERT INTO " + dbname + ".treballs (titol, descripcio, estat, estudis, recursos, dataDefensa, dataCreacio) VALUES ('Els dofins','Els dofins, la seva vida, la seva anatomia, la seva alimentacio.','proposat','Biologia','Wikipedia','2017-10-25','2017-1-22')",
            "INSERT INTO " + dbname + ".tfgVsDirector (treball_id, professor_id) VALUES (1,2)"

        };
        for (String datum : data) {
            if (stmt.executeUpdate(datum) <= 0) {
                messages.add("<span class='error'>Error inserting data: " + datum + "</span>");
                return messages;
            }
            messages.add("<pre> -> " + datum + "<pre>");
        }
        return messages;
    }

    public void jspInit() {
        try {
            List<String> messages = resetDatabase(false);
            for (String message : messages) {
                System.out.println("install.jsp: " + message);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Force database installation</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database initialization in progress</h2>
<%
    List<String> messages = resetDatabase(true);
    for (String message : messages) {
        out.println(message);
    }
%>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
